<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Parada;

class CreateParadasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $user = [
            [
               'rua'=>'Av. Bom Pastor',
               'numero' =>"925",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Luíz Burgos',
               'numero' =>"625",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua São Miguel',
               'numero' =>"447",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua São Miguel',
               'numero' =>"225",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Praça Dom Pedro II',
               'numero' =>"51",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Praça Dom Pedro II',
               'numero' =>"92",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Dom José',
               'numero' =>"180",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Santo Antônio',
               'numero' =>"111",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Doutor José Mariano',
               'numero' =>"522",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Doutor José Mariano',
               'numero' =>"826",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Rui Barbosa',
               'numero' =>"296",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Rui Barbosa',
               'numero' =>"710",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Rui Barbosa',
               'numero' =>"924",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Rui Barbosa',
               'numero' =>"1128",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Simoa Gomes',
               'numero' =>"504",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Simoa Gomes',
               'numero' =>"218",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Simoa Gomes',
               'numero' =>"217",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Simoa Gomes',
               'numero' =>"69",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Caruaru',
               'numero' =>"676",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Caruaru',
               'numero' =>"515",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Avenida Caruaru',
               'numero' =>"508",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Caruaru',
               'numero' =>"323",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Caruaru',
               'numero' =>"165",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Caruaru',
               'numero' =>"115",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Caruaru',
               'numero' =>"106",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Caruaru',
               'numero' =>"S/N",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Coronel Antonio Souto',
               'numero' =>"369",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Coronel Antonio Souto',
               'numero' =>"386",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Coronel Antonio Souto',
               'numero' =>"537",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Capitão Pedro Rodrigues',
               'numero' =>"120",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Capitão Pedro Rodrigues',
               'numero' =>"195",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Capitão Pedro Rodrigues',
               'numero' =>"800",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Capitão Pedro Rodrigues',
               'numero' =>"555",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Capitão Pedro Rodrigues',
               'numero' =>"592",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Capitão Pedro Rodrigues',
               'numero' =>"399",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Praça Tiradentes',
               'numero' =>"",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Dantas Barreto',
               'numero' =>"236",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Terminal Centro',
               'numero' =>"",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Terminal João Da Mata',
               'numero' =>"",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Florianópolis',
               'numero' =>"465",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Florianópolis',
               'numero' =>"319",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Florianópolis',
               'numero' =>"187",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Profa. Júlia Brasileiro Vila Nova',
               'numero' =>"775",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Profa. Júlia Brasileiro Vila Nova',
               'numero' =>"631",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Profa. Júlia Brasileiro Vila Nova',
               'numero' =>"483",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Afonso Pena',
               'numero' =>"190",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Afonso Pena',
               'numero' =>"178",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua São Domingos',
               'numero' =>"214",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Pedro Cavalcante',
               'numero' =>"224",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Pedro Cavalcante',
               'numero' =>"402",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Francisco Gueiros',
               'numero' =>"249",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Francisco Gueiros',
               'numero' =>"309",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Francisco Gueiros',
               'numero' =>"584",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Duque De Caxias',
               'numero' =>"S/N",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Duque De Caxias',
               'numero' =>"258",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Duque De Caxias',
               'numero' =>"339",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Duque De Caxias',
               'numero' =>"636",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Duque De Caxias',
               'numero' =>"671",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Duque De Caxias',
               'numero' =>"759",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Um',
               'numero' =>"740",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Sargento Evandro Marcílio',
               'numero' =>"136",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Sargento Evandro Marcílio',
               'numero' =>"326",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ernesto Nazarem',
               'numero' =>"2",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ernesto Nazarem',
               'numero' =>"188",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ernesto Nazarem',
               'numero' =>"50",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ataúlfo Alves',
               'numero' =>"25",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ataúlfo Alves',
               'numero' =>"75",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ataúlfo Alves',
               'numero' =>"103",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ataúlfo Alves',
               'numero' =>"213",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ataúlfo Alves',
               'numero' =>"271",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ataúlfo Alves',
               'numero' =>"311",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ataúlfo Alves',
               'numero' =>"521",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Três',
               'numero' =>"1",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Três',
               'numero' =>"225",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Um',
               'numero' =>"67",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Júlio Brasileiro',
               'numero' =>"714",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Júlio Brasileiro',
               'numero' =>"1297",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Júlio Brasileiro',
               'numero' =>"1117",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Júlio Brasileiro',
               'numero' =>"1184",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Júlio Brasileiro',
               'numero' =>"1005",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Júlio Brasileiro',
               'numero' =>"1050",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Praça Tavares Correia',
               'numero' =>"1346",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'BR-423',
               'numero' =>"1689",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'BR-423',
               'numero' =>"2000",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'BR-423 (Parada Centro)',
               'numero' =>"S/N",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'BR-424',
               'numero' =>"396",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'PE-177 (Parada 1 - Sentido Subúrbio)',
               'numero' =>"",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'PE-177 (Parada 2 - Sentido Subúrbio)',
               'numero' =>"",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Avenida Irga',
               'numero' =>"1160",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Bom Conselho',
               'numero' =>"58",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Bom Conselho',
               'numero' =>"266",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Saloá',
               'numero' =>"63",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. São João',
               'numero' =>"86",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Caetés',
               'numero' =>"154",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Vital Brasil',
               'numero' =>"673",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Vital Brasil',
               'numero' =>"856",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua João Figueiredo',
               'numero' =>"S/N",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Sitio Paulista',
               'numero' =>"1160",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Sitio Paulista',
               'numero' =>"662",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Sitio Paulista',
               'numero' =>"704",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Sitio Paulista',
               'numero' =>"2444",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Sitio Paulista',
               'numero' =>"2467",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Sitio Paulista',
               'numero' =>"3085",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Terminal Condomínio Colinas',
               'numero' =>"",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua JK',
               'numero' =>"S/N",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Flávio Pereira Brito',
               'numero' =>"214",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua José Ferreira Ferro',
               'numero' =>"246",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Osvaldo Gonçalves Cruz',
               'numero' =>"264",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Carlos Chagas',
               'numero' =>"241",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Terminal Quartel',
               'numero' =>"",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Terminal Indiano',
               'numero' =>"",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Professora Cecília Rodrigues',
               'numero' =>"484",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Professora Cecília Rodrigues',
               'numero' =>"642a",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Padre Agobar Valença',
               'numero' =>"850",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Francisco Paes De Melo',
               'numero' =>"2",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Francisco Paes De Melo',
               'numero' =>"168",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Francisco Paes De Melo',
               'numero' =>"350",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Manoel Pessoa Juvenal',
               'numero' =>"226",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Padre Agobar Valença',
               'numero' =>"555",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Manoel Cipriano Da Cruz',
               'numero' =>"57",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Abílio Camilo Valença',
               'numero' =>"474",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Abílio Camilo Valença',
               'numero' =>"245",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Abílio Camilo Valença',
               'numero' =>"45",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Tavares Correia',
               'numero' =>"245",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Tavares Correia',
               'numero' =>"196",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Tavares Correia',
               'numero' =>"196",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ministro Mario Andreazza',
               'numero' =>"205",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua José Cardoso',
               'numero' =>"147",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua José Cardoso',
               'numero' =>"188",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Jaime Pinheiro De Souza',
               'numero' =>"185",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Jaime Pinheiro De Souza',
               'numero' =>"1",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Sargento Evandro Marcílio',
               'numero' =>"990",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Chico Mendes',
               'numero' =>"38",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Chico Mendes',
               'numero' =>"43",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Cristóvão Colombo',
               'numero' =>"210",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Cristóvão Colombo',
               'numero' =>"319",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Brás Cubas',
               'numero' =>"131",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Brás Cubas',
               'numero' =>"45",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Mauro De Souza Lima Filho',
               'numero' =>"486",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Mauro De Souza Lima Filho',
               'numero' =>"493",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Mauro De Souza Lima Filho',
               'numero' =>"601",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Trinta E Um De Março',
               'numero' =>"121",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Trinta E Um De Março',
               'numero' =>"205",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Trinta E Um De Março',
               'numero' =>"189",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Trinta E Um De Março',
               'numero' =>"481",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Felipe Camarão',
               'numero' =>"1",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Agostinho Branco',
               'numero' =>"273",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Agostinho Branco',
               'numero' =>"306",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Agostinho Branco',
               'numero' =>"526",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Avenida Pedro Cavalcante',
               'numero' =>"403",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Pedro Cavalcante',
               'numero' =>"299",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Pedro Cavalcante',
               'numero' =>"151",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Praça Tavares Correia',
               'numero' =>"23",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Rui Barbosa',
               'numero' =>"1061",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Rui Barbosa',
               'numero' =>"781",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Rui Barbosa',
               'numero' =>"479",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Rui Barbosa',
               'numero' =>"173",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Quinze De Novembro',
               'numero' =>"973",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Quinze De Novembro',
               'numero' =>"143",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Dantas Barreto',
               'numero' =>"405",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Dantas Barreto',
               'numero' =>"236",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Dantas Barreto',
               'numero' =>"236",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. José Leitão',
               'numero' =>"126",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. José Leitão',
               'numero' =>"440",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Sul',
               'numero' =>"2",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Sul',
               'numero' =>"250",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Sul',
               'numero' =>"326",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Sul',
               'numero' =>"472",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Sul',
               'numero' =>"684",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Sul',
               'numero' =>"950",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Deolinda Silvestre Valença',
               'numero' =>"176",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Deolinda Silvestre Valença',
               'numero' =>"152",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Deolinda Silvestre Valença',
               'numero' =>"S/N",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Deolinda Silvestre Valença',
               'numero' =>"72",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Deolinda Silvestre Valença',
               'numero' =>"394",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Deolinda Silvestre Valença',
               'numero' =>"1120",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua João Tiago Filho',
               'numero' =>"85",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Manoel Camelo',
               'numero' =>"4",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Manoel Camelo',
               'numero' =>"5",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Manoel Camelo',
               'numero' =>"65",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Manoel Camelo',
               'numero' =>"71",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Terminal Residencial Manoel Camelo',
               'numero' =>"",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua João Tiago Filho',
               'numero' =>"185",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua João Tiago Filho',
               'numero' =>"284",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ivaldo De Almeida',
               'numero' =>"21",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ivaldo De Almeida',
               'numero' =>"313",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ivaldo De Almeida',
               'numero' =>"401",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Manoel Alves Machado',
               'numero' =>"763",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Manoel Alves Machado',
               'numero' =>"483",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Manoel Alves Machado',
               'numero' =>"433",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Manoel Alves Machado',
               'numero' =>"357",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Manoel Alves Machado',
               'numero' =>"556",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Manoel Alves Machado',
               'numero' =>"127",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Manoel Alves Machado',
               'numero' =>"735",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Manoel Alves Machado',
               'numero' =>"165",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Antônio Machado',
               'numero' =>"55",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Florêncio Rodrigues',
               'numero' =>"186",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Florêncio Rodrigues',
               'numero' =>"167",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Pedro Lima',
               'numero' =>"15",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Altinho',
               'numero' =>"147",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Altinho',
               'numero' =>"15",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Paraguai',
               'numero' =>"384",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Professor Mario Matos',
               'numero' =>"30",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Professor Mario Matos',
               'numero' =>"126",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Professor Mario Matos',
               'numero' =>"735",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Professor Mario Matos',
               'numero' =>"165",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Terminal Cohab 1',
               'numero' =>"",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Terminal Cohab 2',
               'numero' =>"",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Terminal Antônio Cordeiro',
               'numero' =>"",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Radialista Flauberto Elias',
               'numero' =>"639",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Radialista Flauberto Elias',
               'numero' =>"299",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Radialista Flauberto Elias',
               'numero' =>"696",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Radialista Flauberto Elias',
               'numero' =>"1",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Radialista Flauberto Elias',
               'numero' =>"1800",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua João Henrique Araujo',
               'numero' =>"43",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Dois',
               'numero' =>"2",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Dois',
               'numero' =>"63",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Quinze',
               'numero' =>"180",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Arlindo Ouro Preto',
               'numero' =>"337",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Frei Damião',
               'numero' =>"187",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Sátiro Ivo',
               'numero' =>"1087",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Sátiro Ivo',
               'numero' =>"956",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Sátiro Ivo',
               'numero' =>"823",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Sátiro Ivo',
               'numero' =>"132",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Sátiro Ivo',
               'numero' =>"S/N",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Darcy Medeiros',
               'numero' =>"64",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Julião Cavalcante',
               'numero' =>"60",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Julião Cavalcante',
               'numero' =>"398",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Julião Cavalcante',
               'numero' =>"47",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Julião Cavalcante',
               'numero' =>"37",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ernesto Dourado',
               'numero' =>"196",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ernesto Dourado',
               'numero' =>"402",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ernesto Dourado',
               'numero' =>"680",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ernesto Dourado',
               'numero' =>"839",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ernesto Dourado',
               'numero' =>"800",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ernesto Dourado',
               'numero' =>"625",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ernesto Dourado',
               'numero' =>"403",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ernesto Dourado',
               'numero' =>"85",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Coelho Neto',
               'numero' =>"145",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Coelho Neto',
               'numero' =>"280",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Cristóvão Colombo',
               'numero' =>"51",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Cristóvão Colombo',
               'numero' =>"226",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Cristóvão Colombo',
               'numero' =>"338",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Jaime Pinheiro De Souza',
               'numero' =>"2",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Jaime Pinheiro De Souza',
               'numero' =>"492",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Jaime Ovale',
               'numero' =>"141",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Jaime Ovale',
               'numero' =>"362",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Jaime Ovale',
               'numero' =>"608",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Dolores Duran',
               'numero' =>"281",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Terminal Parque Fênix',
               'numero' =>"",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ministro Dilson Funaro',
               'numero' =>"22",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ministro Dilson Funaro',
               'numero' =>"23",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Ministro Dilson Funaro',
               'numero' =>"401",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Loteamento Iranopolis',
               'numero' =>"411",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Projetada',
               'numero' =>"S/N",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Sebastião Paes De Melo',
               'numero' =>"576",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Sebastião Paes De Melo',
               'numero' =>"804",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Sebastião Paes De Melo',
               'numero' =>"932",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Sebastião Paes De Melo',
               'numero' =>"1442",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Sebastião Paes De Melo',
               'numero' =>"1345",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Sebastião Paes De Melo',
               'numero' =>"1838",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Sebastião Paes De Melo',
               'numero' =>"2488",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Sebastião Paes De Melo',
               'numero' =>"2413",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Pascoal Lopes',
               'numero' =>"117",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Pascoal Lopes',
               'numero' =>"117",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Serra Branca',
               'numero' =>"2",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Serra Branca',
               'numero' =>"106",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Oscar Francisco Da Silva',
               'numero' =>"90",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Oscar Francisco Da Silva',
               'numero' =>"S/N",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Oscar Francisco Da Silva',
               'numero' =>"530",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Oscar Francisco Da Silva',
               'numero' =>"662",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Oscar Francisco Da Silva',
               'numero' =>"812",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Oscar Francisco Da Silva',
               'numero' =>"1450",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Oscar Francisco Da Silva',
               'numero' =>"1068",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Terminal Várzea',
               'numero' =>"",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Terminal Cidade Das Flores',
               'numero' =>"",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Marechal Rondon Lot Jd Monte Sinai',
               'numero' =>"89",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Professor Ageu Viêira',
               'numero' =>"121",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Da Luís Rodão De Araújo',
               'numero' =>"586",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Capitao Valdemar Viana',
               'numero' =>"90",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Avenida Monsenhor Arruda Câmara',
               'numero' =>"52",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Avenida Monsenhor Arruda Câmara',
               'numero' =>"147",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Josenildo Henrique Saraiva Dos Santos',
               'numero' =>"569",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Josenildo Henrique Saraiva Dos Santos',
               'numero' =>"725",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Josenildo Henrique Saraiva Dos Santos',
               'numero' =>"726",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Estrada De São Pedro',
               'numero' =>"470",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Estrada De São Pedro',
               'numero' =>"75",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Estrada De São Pedro',
               'numero' =>"S/N",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua José Bezerra Lins',
               'numero' =>"19",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua José Bezerra Lins',
               'numero' =>"51",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Terminal Viana & Moura',
               'numero' =>"",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua São Vicente',
               'numero' =>"104",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua São Domingos',
               'numero' =>"347",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua São Domingos',
               'numero' =>"214",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua São Domingos',
               'numero' =>"214",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Barão De Nazaré',
               'numero' =>"1415",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Barão De Nazaré',
               'numero' =>"1353",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Barão De Nazaré',
               'numero' =>"1227",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Barão De Nazaré',
               'numero' =>"1003",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Barão De Nazaré',
               'numero' =>"1030",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Barão De Nazaré',
               'numero' =>"654",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Barão De Nazaré',
               'numero' =>"620",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Terminal Brasília',
               'numero' =>"",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Capitão Pedro Rodrigue',
               'numero' =>"800",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Capitão Pedro Rodrigue',
               'numero' =>"555",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Capitão Pedro Rodrigue',
               'numero' =>"592",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Capitão Pedro Rodrigue',
               'numero' =>"399",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Capitão Pedro Rodrigue',
               'numero' =>"195",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Capitão Pedro Rodrigue',
               'numero' =>"120",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Paulo Afonso',
               'numero' =>"198",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Paulo Afonso',
               'numero' =>"408",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Getulio Jobby Jr',
               'numero' =>"11",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua São Vicente',
               'numero' =>"S/N",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Jornalista Almir Alves',
               'numero' =>"S/N",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Estrada Do Aeroporto',
               'numero' =>"S/N",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Estrada Do Aerporto (Terminal)',
               'numero' =>"S/N",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Euclides Dourado',
               'numero' =>"720",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Av. Euclides Dourado',
               'numero' =>"830",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Da Liberdade',
               'numero' =>"523",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Da Liberdade',
               'numero' =>"697",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Da Liberdade',
               'numero' =>"894",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Da Liberdade',
               'numero' =>"17",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Da Liberdade',
               'numero' =>"97",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Da Liberdade',
               'numero' =>"934",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Da Liberdade',
               'numero' =>"1274",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Da Liberdade',
               'numero' =>"1378",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Da Liberdade',
               'numero' =>"1274",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Da Liberdade',
               'numero' =>"1311",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Da Liberdade',
               'numero' =>"1203",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Da Liberdade',
               'numero' =>"1785",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Avenida Santa Rosa',
               'numero' =>"760",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Dos Operários',
               'numero' =>"630",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Terminal Liberdade',
               'numero' =>"",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Coronel Antônio Victor',
               'numero' =>"355",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Praça Mestre Dominguinhos',
               'numero' =>"101",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Voluntários Da Pátria',
               'numero' =>"356",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Voluntários Da Pátria',
               'numero' =>"484",
               'latitude'=>0,
               'longitude'=>0,
            ],
            [
               'rua'=>'Rua Voluntários Da Pátria',
               'numero' =>"586",
               'latitude'=>0,
               'longitude'=>0,
            ],
        ];
  
        foreach ($user as $key => $value) {
            Parada::create($value);
        }
    }
}
